apiVersion: v1
kind: Service
metadata:
  name: httpbin-go
  labels:
    app: httpbin-go
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: httpbin-go
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-go
  labels:
    app: httpbin-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin-go
  template:
    metadata:
      labels:
        app: httpbin-go
    spec:
      containers:
      - name: httpbin-go
        image: gamussa/httpbin-go
        imagePullPolicy: Always
